CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR                     NOT NULL,
    email   VARCHAR                     NOT NULL UNIQUE,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS subscribers
(
    user_id BIGINT NOT NULL,
    sub_id  BIGINT NOT NULL,
    CONSTRAINT sub_pk PRIMARY KEY (user_id, sub_id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR NOT NULL,
    description VARCHAR
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR                     NOT NULL,
    annotation         VARCHAR                     NOT NULL,
    description        VARCHAR                     NOT NULL,
    creator            BIGINT REFERENCES users (id),
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    paid               BOOLEAN                     NOT NULL,
    cost               INTEGER,
    category_id        INTEGER REFERENCES categories (id),
    participant_limit  INTEGER                     NOT NULL,
    request_moderation BOOLEAN                     NOT NULL,
    status             VARCHAR                     NOT NULL,
    created            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published          TIMESTAMP,
    lat                DECIMAL,
    lon                DECIMAL
);

CREATE TABLE IF NOT EXISTS participants
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT REFERENCES users (id),
    event_id BIGINT REFERENCES events (id),
    status   VARCHAR                     NOT NULL,
    created  TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR NOT NULL UNIQUE,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id BIGINT REFERENCES compilations (id),
    event_id       BIGINT REFERENCES events (id),
    CONSTRAINT pk PRIMARY KEY (compilation_id, event_id)
);